/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package invoiceproject.view;

import invoiceproject.controller.actions;
import java.awt.HeadlessException;
import javax.swing.JButton;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Home
 */
public class invoiceframe extends javax.swing.JFrame {

    /**
     * Creates new form invoiceframe
     */
    public invoiceframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Addinvoice = new javax.swing.JButton();
        Addinvoice.setActionCommand("addinvoice");
        Addinvoice.addActionListener(action);
        deleteinvoice = new javax.swing.JButton();
        deleteinvoice.setActionCommand("deleteinvoice");
        deleteinvoice.addActionListener(action);
        savedetail = new javax.swing.JButton();
        savedetail.setActionCommand("savedetails");
        savedetail.addActionListener(action);
        canceldetail = new javax.swing.JButton();
        canceldetail.setActionCommand("canceldetail");
        canceldetail.addActionListener(action);
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.getSelectionModel().addListSelectionListener(action);
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        invoicenumber = new javax.swing.JTextField();
        invoicedate = new javax.swing.JTextField();
        customername = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        addline = new javax.swing.JButton();
        addline.setActionCommand("addinvoiceline");
        addline.addActionListener(action);
        deleteline = new javax.swing.JButton();
        deleteline.setActionCommand("deleteinvoiceline");
        deleteline.addActionListener(action);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem1.setActionCommand("load");
        jMenuItem1.addActionListener(action);
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem2.setActionCommand("saveall");
        jMenuItem2.addActionListener(action);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Addinvoice.setLabel("Add invoice");

        deleteinvoice.setText("Delete invoice");

        savedetail.setText("Save");
        savedetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savedetailActionPerformed(evt);
            }
        });

        canceldetail.setText("Cancel");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "customer id", "customer name", "customer date ", "invoice total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "customer id", "item name", "price", "count"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("Invoice number");

        jLabel2.setText("Invoice date ");

        jLabel3.setText("Customer name");

        jLabel4.setText("Total");

        invoicenumber.setMinimumSize(new java.awt.Dimension(20, 22));
        invoicenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoicenumberActionPerformed(evt);
            }
        });

        addline.setText("Add line ");

        deleteline.setText("Delete line");
        deleteline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletelineActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("load");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Save");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(invoicenumber, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(invoicedate)
                            .addComponent(customername)
                            .addComponent(total))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(Addinvoice)
                .addGap(58, 58, 58)
                .addComponent(deleteinvoice)
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addline)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteline))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(savedetail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                        .addComponent(canceldetail)))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(invoicenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(invoicedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(customername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addline)
                    .addComponent(deleteline))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addinvoice)
                    .addComponent(deleteinvoice)
                    .addComponent(savedetail)
                    .addComponent(canceldetail))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savedetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savedetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savedetailActionPerformed

    private void invoicenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoicenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invoicenumberActionPerformed

    private void deletelineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletelineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletelineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(invoiceframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(invoiceframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(invoiceframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(invoiceframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               invoiceframe fram=new invoiceframe();
               fram.setVisible(true);
             //fram.action=new actions(fram);
              //String x="E:\\FWD\\sales-invoice-generator\\Sales Invoice Generator\\InvoiceHeader.csv";
              //String y="E:\\FWD\\sales-invoice-generator\\Sales Invoice Generator\\InvoiceLine.csv";
                 String x="src\\invoiceproject\\InvoiceHeader.csv";
              String y="src\\invoiceproject\\InvoiceLine.csv";
              fram.action.load(x, y);
          


              
                //new invoiceframe().setVisible(true);
         //    setjTable1(new JTable(action.load(x,y)));
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addinvoice;
    private javax.swing.JButton addline;
    private javax.swing.JButton canceldetail;
    private javax.swing.JTextField customername;
    private javax.swing.JButton deleteinvoice;
    private javax.swing.JButton deleteline;
    private javax.swing.JTextField invoicedate;
    private javax.swing.JTextField invoicenumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton savedetail;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables

   public actions action=new actions(this);

    public JButton getCanceldetail() {
        return canceldetail;
    }

    public void setCanceldetail(JButton canceldetail) {
        this.canceldetail = canceldetail;
    }

    public JTextField getCustomername() {
        return customername;
    }

    public void setCustomername(JTextField customername) {
        this.customername = customername;
    }

    public JButton getDeleteinvoice() {
        return deleteinvoice;
    }

    public void setDeleteinvoice(JButton deleteinvoice) {
        this.deleteinvoice = deleteinvoice;
    }

    public JTextField getInvoicedate() {
        return invoicedate;
    }

    public void setInvoicedate(JTextField invoicedate) {
        this.invoicedate = invoicedate;
    }

    public JTextField getInvoicenumber() {
        return invoicenumber;
    }

    public void setInvoicenumber(JTextField invoicenumber) {
        this.invoicenumber = invoicenumber;
    }

    public JButton getSavedetail() {
        return savedetail;
    }

    public void setSavedetail(JButton savedetail) {
        this.savedetail = savedetail;
    }

    public JTextField getTotal() {
        return total;
    }

    public void setTotal(JTextField total) {
        this.total = total;
    }

    /**
     * Get the value of action
     *
     * @return the value of action
     */
  /*  public actions getAction() {
        return action;
    }
*/
    /**
     * Set the value of action
     *
     * @param action new value of action
     */
    /*public void setAction(actions action) {
        this.action = action;
    }*/

    public JTable getjTable1() {
        return jTable1;
    }
    

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTable getjTable2() {
        return jTable2;
    }

    public void setjTable2(JTable jTable2) {
        this.jTable2 = jTable2;
    }
}
